<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '汽车',
    'cat_logo' => '',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '4',
    'level' => 0,
    'id' => '1',
    'name' => '汽车',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '奥迪',
    'cat_logo' => '1497016763990882049.jpg',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => '奥迪',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '一汽大众奥迪',
    'cat_logo' => '',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 2,
    'id' => '3',
    'name' => '一汽大众奥迪',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '奥迪A6',
    'cat_logo' => '1497016826071620721.jpg',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 3,
    'id' => '4',
    'name' => '奥迪A6',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '2004款1.8T(125马力)',
    'cat_logo' => '',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 4,
    'id' => '9',
    'name' => '2004款1.8T(125马力)',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '2004款1.8T手动基本',
    'cat_logo' => '',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 4,
    'id' => '10',
    'name' => '2004款1.8T手动基本',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '奥迪A4L',
    'cat_logo' => '1497016853411446705.jpg',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '5',
    'name' => '奥迪A4L',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '奥迪Q3',
    'cat_logo' => '1497016865829549008.jpg',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '6',
    'name' => '奥迪Q3',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '奥迪进口',
    'cat_logo' => '',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '2',
    'level' => 2,
    'id' => '7',
    'name' => '奥迪进口',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '奥迪R18',
    'cat_logo' => '1497016925153393759.jpg',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 3,
    'id' => '8',
    'name' => '奥迪R18',
  ),
);
?>